module.exports = {
	Cache: require("./Cache.js"),
	ConversionHandler: require("./ConversionHandler.js"),
	Encryption: require("./Encryption"),
	ExtensionRunner: require("./ExtensionRunner.js"),
	getGuild: require("./GetGuild.js"),
	Giphy: require("./Giphy"),
	Giveaways: require("./Giveaways.js"),
	Imgur: require("./Imgur"),
	Lotteries: require("./Lotteries.js"),
	MarkdownTable: require("./MarkdownTable.js"),
	MessageUtils: require("./MessageUtils/index"),
	MicrosoftTranslate: require("./MicrosoftTranslate.js"),
	ModLog: require("./ModLog.js"),
	NewServer: require("./NewServer.js"),
	Polls: require("./Polls.js"),
	PostShardedData: require("./PostShardedData.js"),
	PostTotalData: require("./PostTotalData.js"),
	RandomAnimals: require("./RandomAnimals.js"),
	StringJS: require("./String"),
	Traffic: require("./Traffic.js"),
	Trivia: require("./Trivia.js"),
	Updater: require("./Updater.js"),
	Utils: require("./Utils/index"),
};
