module.exports = {
	Boot: require("./Boot.js"),
	Cache: require("./Cache.js"),
	Console: require("./Console.js"),
	ExtensionRunner: require("./ExtensionRunner.js"),
	GetGuild: require("./GetGuild.js"),
	Giveaways: require("./Giveaways.js"),
	Imgur: require("./Imgur"),
	Lotteries: require("./Lotteries.js"),
	MarkdownTable: require("./MarkdownTable.js"),
	MessageUtils: require("./MessageUtils/index"),
	MicrosoftTranslate: require("./MicrosoftTranslate.js"),
	ModLog: require("./ModLog.js"),
	NewServer: require("./NewServer.js"),
	Polls: require("./Polls.js"),
	PostShardedData: require("./PostShardedData.js"),
	PostTotalData: require("./PostTotalData.js"),
	RandomAnimals: require("./RandomAnimals.js"),
	Sharder: require("./Sharder.js"),
	SharderIPC: require("./IPC.js"),
	Traffic: require("./Traffic.js"),
	Trivia: require("./Trivia.js"),
	Updater: require("./Updater.js"),
	Utils: require("./Utils/index"),
};
