module.exports = {
	ClearServerStats: require("./ClearServerStats.js"),
	FilterChecker: require("./FilterChecker.js"),
	GetValue: require("./GetValue.js"),
	Gist: require("./GitHubGist.js"),
	GlobalDefines: require("./GlobalDefines.js"),
	IsURL: url => /^http?/gim.test(url),
	MessageOfTheDay: require("./MessageOfTheDay.js"),
	ObjectDefines: require("./ObjectDefines.js"),
	PromiseWait: waitFor => new Promise(resolve => setTimeout(resolve, waitFor)),
	RankScoreCalculator: (messages, voice) => messages + voice,
	RegExpMaker: require("./RegExpMaker.js"),
	RSS: require("./RSS.js"),
	SearchiTunes: require("./SearchiTunes.js"),
	SetCountdown: require("./SetCountdown.js"),
	SetReminder: require("./SetReminder.js"),
	StreamChecker: require("./StreamChecker.js"),
	StreamerUtils: require("./StreamerUtils.js"),
	StreamingRSS: require("./StreamingRSS.js"),
	StructureExtender: require("./StructureExtender.js"),
};
